### ISSUE TITLE
侵入性教强

### ISSUE THREAD

**Issue by PeterXiaosa** [liudao01/EventCollect#5]
为了收集用户信息，感觉对代码侵入性较强。比如按钮的点击事件中需要手动内置appCollectUtil.attributeCollect函数。重写一个onCLickListener然后在其中实现该方法感觉侵入性还是教强，想知道有没有侵入性比较低的方案呢？

**Comment by liudao01** [comment]
这种侵入性强的是需要自定义参数的  如果不自定义参数 那就用默认的就行了
